In [5]:
#numpy：
#功能：提供高效数组 支持批量数学运算 适合矩阵、统计、科学计算
#意义：计算更快 代码更简洁 很多数据分析和机器学习库都依赖它

import numpy as np
import pandas as pd 

arry =np.array([[1,2,3],[4,5,6]])
print(arry)

print(arry.shape)  #输出数组的形状(行列)
print(arry.ndim)  #输出数组的维度（行）
print(arry.size)  #输出数组的元素个数（行*列）
print(arry.dtype)  #输出数组的元素类型 （数据类型）



[[1 2 3]
 [4 5 6]]
(2, 3)
2
6
int64


In [ ]:
#numpy 创建arry

import numpy as np

 # 创建一维数组，指定数据类型为浮点数
a = np.array([1.2, 23, 3], dtype=float) 
print(a)  # 输出没有逗号分隔
print(a.dtype)  # 输出数组的元素类型（数据类型）


#创建3行4列的二维数组，元素全为0, np.ones() 创建全为1的数组
b=np.zeros((3,4), dtype=int)  
print(b)


#创建序列 arange：重点是间隔  linspace：重点是数量
print("创建1-10的等差数列，步长为2")
c=np.arange(1,10,2)  #创建等差数列，起始值，终止值，步长
print(c)

print("创建0-9的等差数列，重塑为2行5列")
c=np.arange(10).reshape(2,5)  #创建0-9的等差数列，重塑为2行5列
print(c)

print("创建1-10的等差数列")
c=np.linspace(1,10,5)  #创建等差数列，起始值，终止值，元素个数
print(c)



[ 1.2 23.   3. ]
float64
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
创建1-10的等差数列，步长为2
[1 3 5 7 9]
创建0-9的等差数列，重塑为2行5列
[[0 1 2 3 4]
 [5 6 7 8 9]]
创建1-10的等差数列
[ 1.    3.25  5.5   7.75 10.  ]


In [ ]:
#numpy基础运算

import numpy as np

a=np.array([10,20,30,40])
b=np.arange(4)

print("a-b")
print(a,b)
c=a-b #逐个相减 +-*/
print(c)

print("a**2")  #平方
c=a**2  #平方
print(c)

print("10*np.sin(a)")  #三角函数
c=10*np.sin(a)  #三角函数
print(c)

print("a<10")  #比较运算
print(a<10)


#矩阵乘法
A = np.array([[1, 1],
              [0, 1]])
B = np.array([[2, 0],
              [3, 4]])
print("A:")
print(A)
print("B:")
print(B)
print("A * B:")
print(A * B)  # 元素级乘法 对应位置相乘
print("A @ B:")  # 矩阵乘法 线代相乘
print(A @ B)

#矩阵乘法（线代）的写法2
print("np.dot(A, B):")
print(np.dot(A, B))
#矩阵乘法（线代）的写法3
print("A.dot(B):")
print(A.dot(B))





a-b
[10 20 30 40] [0 1 2 3]
[10 19 28 37]
a**2
[ 100  400  900 1600]
10*np.sin(a)
[-5.44021111  9.12945251 -9.88031624  7.4511316 ]
a<10
[False False False False]
A:
[[1 1]
 [0 1]]
B:
[[2 0]
 [3 4]]
A * B:
[[2 0]
 [0 4]]
A @ B:
[[5 4]
 [3 4]]
np.dot(A, B):
[[5 4]
 [3 4]]
A.dot(B):
[[5 4]
 [3 4]]


In [ ]:
#矩阵基础运算
import numpy as np
a=np.random.random((2,4))  #创建2行4列的随机数组
print(a)

print("np.sum(a)")  #求和
print(np.sum(a))  
print("np.min(a,axis=0),按列求最小值")  #按列求最小值
print(np.min(a, axis=0)) 
print("np.min(a,axis=1),按行求最小值")  #按行求最小值
print(np.min(a, axis=1)) 
print("np.max(a),求最大值")  #求最大值
print(np.max(a)) 



[[0.68768267 0.15013054 0.13381912 0.3797539 ]
 [0.28531634 0.24436144 0.03362398 0.10153445]]
np.sum(a)
2.016222440471527
np.min(a,axis=0),按列求最小值
[0.28531634 0.15013054 0.03362398 0.10153445]
np.min(a,axis=1),按行求最小值
[0.13381912 0.03362398]
np.max(a),求最大值
0.687682665901567
