In [ ]:
#numpy基础运算2
import numpy as np

A=np.arange(2,14).reshape(3,4)
print(A)

print("返回最小值索引")
print(np.argmin(A)) 

print("返回最大值索引")
print(np.argmax(A))

print("平均值")
print(np.mean(A))
print(A.mean())

print("平均值按行计算")
print(np.mean(A,axis=1))#按行计算平均值

print("中位数")
print(np.median(A))#(7+8)/2

print("返回数组元素的累积和")
print(np.cumsum(A))#本身加上前面所有数字的和

print("返回数组元素的累差")
print(np.diff(A))#本身减去前面所有数字的差

#返回非零元素的索引，第一行是行索引，第二行是列索引
print("找出数组中非零元素的索引")
print(np.nonzero(A))



[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]]
返回最小值索引
0
返回最大值索引
11
平均值
7.5
7.5
中位数
7.5
返回数组元素的累积和
[ 2  5  9 14 20 27 35 44 54 65 77 90]
返回数组元素的累差
[[1 1 1]
 [1 1 1]
 [1 1 1]]
找出数组中非零元素的索引
(array([0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2]), array([0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3]))


In [ ]:
print("排序")
print(np.sort(A))#按行排序

print("转置")
print(A.T)
print(A.transpose())#转置:行变列

print(A.T.dot(A))#矩阵乘法(矩阵乘转置矩阵)

print("clip函数")
print(np.clip(A,5,9))#小于5的变为5，大于9的变为9



排序
[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]]
转置
[[ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]
 [ 5  9 13]]
[[ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]
 [ 5  9 13]]
[[140 158 176 194]
 [158 179 200 221]
 [176 200 224 248]
 [194 221 248 275]]
clip函数
[[5 5 5 5]
 [6 7 8 9]
 [9 9 9 9]]
平均值按行计算
[ 3.5  7.5 11.5]


In [ ]:
#numpy索引


A = np.arange(3, 15)
print(A)

print("索引单个元素")
print(A[1])  # 第二个元素

print("切片")
print(A[1:3])  # 第二个到第三个元素

print("布尔索引")
print(A[A > 5])  # 大于5的元素


A=np.arange(2,14).reshape(3,4)
print(A)

print("索引单个元素")
print(A[1,2])  # 第二行第三列的元素
print(A[1][2])

print("第二行所有元素")
print(A[1])
print(A[1,:])  # 第二行所有元素

print("第二列所有元素")
print(A[:,1])  # 第二列所有元素

print("切片")
print(A[1:3, 1:3])  # 第二行到第三行，第二列到第三列的元素




[ 3  4  5  6  7  8  9 10 11 12 13 14]
索引单个元素
4
切片
[4 5]
布尔索引
[ 6  7  8  9 10 11 12 13 14]
[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]]
索引单个元素
8
8
第二行所有元素
[6 7 8 9]
[6 7 8 9]
第二列所有元素
[ 3  7 11]
切片
[[ 7  8]
 [11 12]]


In [ ]:
print("按行遍历数组")
for row in A:
    print(row)

print("按列遍历数组")
for col in A.T:
    print(col)

print("将多维数组降为一维数组")
print(A.flatten())
print("使用flat属性返回一个迭代器")
print(A.flat)  # 返回一个迭代器

print("使用flat属性遍历数组")
for item in A.flat:
    print(item)




按行遍历数组
[2 3 4 5]
[6 7 8 9]
[10 11 12 13]
按列遍历数组
[ 2  6 10]
[ 3  7 11]
[ 4  8 12]
[ 5  9 13]
将多维数组降为一维数组
[ 2  3  4  5  6  7  8  9 10 11 12 13]
使用flat属性返回一个迭代器
使用flat属性遍历数组
2
3
4
5
6
7
8
9
10
11
12
13


In [53]:
#array合并
import numpy as np
A=np.array([1,1,1])
B=np.array([2,2,2])

print("垂直合并数组")
print(np.vstack((A,B)))#垂直合并
print("水平合并数组")
print(np.hstack((A,B)))#水平合并

print("增加一个维度横向")
print(A[np.newaxis,:])#增加一个维度
print(A[np.newaxis,:].shape)#(1,3)

print("增加一个维度纵向")
print(A[:,np.newaxis])#增加一个维度
print(A[:,np.newaxis].shape)#(3,1)

A=np.array([1,1,1])[:,np.newaxis]#竖
B=np.array([2,2,2])[:,np.newaxis]#竖
print(A)
print(B)

print("垂直合并数组")
print(np.vstack((A,B)))#垂直合并
print("水平合并数组")
print(np.hstack((A,B)))#水平合并


垂直合并数组
[[1 1 1]
 [2 2 2]]
水平合并数组
[1 1 1 2 2 2]
增加一个维度横向
[[1 1 1]]
(1, 3)
增加一个维度纵向
[[1]
 [1]
 [1]]
(3, 1)
[[1]
 [1]
 [1]]
[[2]
 [2]
 [2]]
垂直合并数组
[[1]
 [1]
 [1]
 [2]
 [2]
 [2]]
水平合并数组
[[1 2]
 [1 2]
 [1 2]]


In [ ]:
print("使用concatenate函数横向合并数组")
C=np.concatenate((A,B), axis=1)#横
print(C)

print("使用concatenate函数纵向合并数组")
D=np.concatenate((A,B), axis=0)#纵
print(D)


使用concatenate函数横向合并数组
[[1 2]
 [1 2]
 [1 2]]
使用concatenate函数纵向合并数组
[[1]
 [1]
 [1]
 [2]
 [2]
 [2]]


In [72]:
import numpy as np
A=np.arange(12).reshape(3,4)
print(A)

print("按列分割")
print(np.split(A,2,axis=1))#按列分割
print("按行分割")   
print(np.split(A,3,axis=0))#按行分割

print("按列分割为不等份")
print(np.array_split(A,3,axis=1))#按列分割为不等份

print("按行分割为不等份")
print(np.array_split(A,2,axis=0))#按行分割为不等份





[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
按列分割
[array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11]])]
按行分割
[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]
按列分割为不等份
[array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2],
       [ 6],
       [10]]), array([[ 3],
       [ 7],
       [11]])]
按行分割为不等份
[array([[0, 1, 2, 3],
       [4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]


In [85]:
#copy & deepcopy
import numpy as np

print("原数组")
a=np.arange(4)
print(a)
b=a#浅拷贝
c=a
d=b
a[0]=11
print("浅拷贝后修改原数组")#改变一个影响全部
print(a)
print(b)
print(c)
print(d)
print("b is a:",b is a  )
print("c is a:",c is a  )
print("d is a:",d is a  )

d[1:3]=[22,33]
print("浅拷贝后修改b数组")#改变一个影响全部
print(a)
print(b)
print(c)
print(d)

#深拷贝
b=a.copy()#深拷贝
print("深拷贝后修改原数组")#改变一个不影响另一个    
print(a)
print(b)
a[0]=111
print("深拷贝后修改原数组")#改变一个不影响另一个
print(a)
print(b)


原数组
[0 1 2 3]
浅拷贝后修改原数组
[11  1  2  3]
[11  1  2  3]
[11  1  2  3]
[11  1  2  3]
b is a: True
c is a: True
d is a: True
浅拷贝后修改b数组
[11 22 33  3]
[11 22 33  3]
[11 22 33  3]
[11 22 33  3]
深拷贝后修改原数组
[11 22 33  3]
[11 22 33  3]
深拷贝后修改原数组
[111  22  33   3]
[11 22 33  3]
